server:
  port: 8085
spring:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
    name: English_Test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.130:3306/English_Test?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.136.130
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  type-aliases-package: com.example.english_test.mapper
logging:
  level:
    com.hmdp: debug

